name: cpp-mingw-prebuilt-release-actions-workflow
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
      - 'c*'

jobs:
  build:
    name: Create Release
    runs-on: windows-latest
    env:
      libraryName: libassuan
      installationPath: libassuan-installation
      mingwTargetZip: libassuan-${{ github.ref_name }}-mingw64-x86_64-posix-seh-rev0-8.1.0.zip
    steps:
      # - shell: cmd
      #   run: |
      #     curl https://gnupg.org/ftp/gcrypt/libassuan/libassuan-2.5.6.tar.bz2 -L -O -J &&^
      #     tar -jxvf libassuan-2.5.6.tar.bz2 &&^
      #     run: rename libassuan-2.5.6 libassuan
      - uses: actions/checkout@v3
      
      - name: Install MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          install: make autoconf automake libtool autogen perl

      - shell: cmd
        run: |
          curl https://github.com/dirkarnez/libgpg-error-prebuilt/releases/download/v1.47/libgpg-error-v1.47-mingw64-x86_64-posix-seh-rev0-8.1.0.zip -L -O -J &&^
          7z.exe x libgpg-error-v1.47-mingw64-x86_64-posix-seh-rev0-8.1.0.zip -o"libgpg-error-v1.47-mingw64-x86_64-posix-seh-rev0-8.1.0"
        
      - name: curl x86_64-8.1.0-release-posix-seh-rt_v6-rev0.7z
        shell: cmd
        run:  curl https://github.com/2641797006/c/blob/master/GCC-zip/x86_64-8.1.0-release-posix-seh-rt_v6-rev0.7z?raw=true -L --output x86_64-8.1.0-release-posix-seh-rt_v6-rev0.7z && dir && 7z.exe x x86_64-8.1.0-release-posix-seh-rt_v6-rev0.7z
      
      - name: curl PortableGit-2.38.1-64-bit.7z.exe
        shell: cmd
        run:  curl https://github.com/git-for-windows/git/releases/download/v2.38.1.windows.1/PortableGit-2.38.1-64-bit.7z.exe -L --output PortableGit-2.38.1-64-bit.7z.exe && dir && 7z.exe x PortableGit-2.38.1-64-bit.7z.exe -o"${{ github.workspace }}\PortableGit-2.38.1-64-bit"
        
      - shell: cmd
        run: |
          .\PortableGit-2.38.1-64-bit\usr\bin\tar.exe -jxvf libassuan-2.5.6.tar.bz2 &&^
          rename libassuan-2.5.6 libassuan
          
      - shell: msys2 {0}
        run: |
          cd libgpg-error-v1.47-mingw64-x86_64-posix-seh-rev0-8.1.0 &&
          ls &&
          cd .. &&
          sed -i 's/prefix=\/d\/a\/libgpg-error-prebuilt\/libgpg-error-prebuilt\/libgpg-error\/libgpg-error-installation/prefix=$(pwd)/g' ./bin/gpg-error-config
      
      - shell: cmd
        run: |
          cd libgpg-error-v1.47-mingw64-x86_64-posix-seh-rev0-8.1.0\bin &&^
          type gpg-error-config
          
      - name: set PATH, check mingw version, cmake generate, build and install
        shell: msys2 {0}
        run: |
            workspace=$(pwd) &&
            cd libgpg-error-v1.47-mingw64-x86_64-posix-seh-rev0-8.1.0 &&
            libgpg_error_location=$(pwd)
            ls &&
            cd .. &&
            export PATH="$workspace/mingw64:$workspace/mingw64/bin:$workspace/PortableGit-2.38.1-64-bit:$workspace/PortableGit-2.38.1-64-bit/bin:$workspace/msys64/usr/bin:/usr/bin" &&
            cd libassuan && 
            g++ --version &&
            ./configure --help &&
            ./configure --with-libgpg-error-prefix="$libgpg_error_location" --disable-shared --disable-tests --prefix="$(pwd)/${{ env.installationPath }}" &&
            make VERBOSE=1 && make install
            
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          directory: "libassuan/${{ env.installationPath }}"
          filename: "${{ env.mingwTargetZip }}"
       
      - name: Release prebuilt
        uses: ncipollo/release-action@v1
        with:
          artifacts: "libassuan/${{ env.installationPath }}/${{ env.mingwTargetZip }}"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}

